diaactual = int()
mesactual = int()
anioactual = int()
diafuturo = int()
mesfuturo = int()
aniofuturo = int()
diasfaltantes = int()
print("Ingrese la fecha actual:")
diaactual = int(input("Día: "))
mesactual = int(input("Mes: "))
anioactual = int(input("Año: "))
print("Ingrese la fecha futura:")
diafuturo = int(input("Día: "))
mesfuturo = int(input("Mes: "))
aniofuturo = int(input("Año: "))
diasfaltantes = ((aniofuturo-anioactual)*365)+((mesfuturo-mesactual)*30)+(diafuturo-diaactual)
print("Número de días faltantes: ",diasfaltantes)

